create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  card_id bigint null references public.cards(id) on delete set null,
  session_id text not null,
  search_term text null,
  metadata jsonb null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists analytics_events_name_created_idx
  on public.analytics_events (event_name, created_at desc);

create index if not exists analytics_events_card_created_idx
  on public.analytics_events (card_id, created_at desc);

create index if not exists analytics_events_session_created_idx
  on public.analytics_events (session_id, created_at desc);

alter table public.analytics_events enable row level security;

drop policy if exists "Service role can manage analytics events" on public.analytics_events;
create policy "Service role can manage analytics events"
on public.analytics_events
for all
to service_role
using (true)
with check (true);
